### ISSUE TITLE
Material Design, NOT AN ISSUE

### ISSUE THREAD

**Issue by gmorel4** [LTBuses/LTB-android#2]
I know this isn't detrimental to the function of the app, but Googles new Material Design philosophy looks pretty awesome.

**Comment by Cyborg572** [comment]
![ltbusses-material-1](https://cloud.githubusercontent.com/assets/842710/12369049/e07817a0-bbbf-11e5-930c-628890211a17.png)

I'm starting to experiment a bit with this. All I've done so far is switch to the default material design theme with custom colours for phones that support it. Nothing broke, so that's promising.

**Comment by Cyborg572** [comment]
I'm closing this issue as I've moved the project to GitLab.  The migrated version of the issue is here: https://gitlab.com/LTBuses/LTB-android/issues/2
